### PR TITLE
Fixed removeChild() error

### PR DESCRIPTION
**Pull request by SjoerdHekking**
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. Is fixed in this commit.

### CODE REVIEW

**Comment by betaWeb** [comment]
@SjoerdHekking you've only changed the .min file ?

**Comment by SjoerdHekking** [comment]
I could only find that file, and all other files depend on only that file. There is no `non` min file? Could you point me to what else should've been changed?

**Comment by betaWeb** [comment]
> I could only find that file, and all other files depend on only that file. There is no `non` min file? Could you point me to what else should've been changed?

https://github.com/betaWeb/flashjs/blob/master/src/FlashMessage.js#L191 that file

**Comment by SjoerdHekking** [comment]
My bad, also updated that one!

**Pull request closed without merging**
